sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t abubaker/docker-react -f dockerfile.dev .

script:
  - docker run -e CI=true abubaker/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker-react'
  env: 'dockerreact-env'
  bucket_name: 'elasticbeanstalk-us-east-1-958537364043'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_Key: "$AWS_SECRET_KEY"