sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t abubaker/docker-react -f dockerfile.dev .

script:
  - docker run -e CI=true abubaker/docker-react npm run test
